### ISSUE TITLE
implement heuristics

### ISSUE THREAD

**Issue by KiaraGrouwstra** [tycho01/sat-sudoku#11]
depends on #8 for bookkeeping on where variables occur.

in order of priority (should only need 2):

- [ ] [Bohm](https://skatgame.net/mburo/ps/satreport.pdf#page=6): gives preference to variables that are satisfying small clauses or that are reducing the size of already small clauses

![image](https://user-images.githubusercontent.com/3059397/53259506-880a0900-36cf-11e9-9dd7-e828fa4ce29e.png)

- [ ] MOM

![image](https://user-images.githubusercontent.com/3059397/53258804-d1f1ef80-36cd-11e9-9aa3-ea11c3a2ddab.png)

- [x] Jeroslow-Wang

![image](https://user-images.githubusercontent.com/3059397/53258772-c3a3d380-36cd-11e9-8a2d-8c013f404f84.png)

- [ ] DLIS max:
DLIS (Dynamic Largest Individual Sum):
  - Pick v with largest CP(v) or largest CN(v)
  - If CP(v) > CN(v) then v=1 else v=0

- [ ] DLIS min

- [ ] random forest (solution as y, state at split as x)

- [ ] pareto dominant

- [ ] next

- [ ] conflict-based stuff

**Comment by gkudva96** [comment]
- [x] Random

- [x] DLIS

- [x] JS-TS
